services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 live_broadcast.asgi:application
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles 
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=live_broadcast.settings
      - DJANGO_DEBUG=True

volumes:
  redis_data: